"""Update models to use UUID primary keys

Revision ID: 20f074aecb6d
Revises:
Create Date: 2023-07-05 13:12:42.801460

"""
from alembic import op
import sqlalchemy as sa
import uuid


# revision identifiers, used by Alembic.
revision = '20f074aecb6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gameplay_images', schema=None) as batch_op:
        batch_op.alter_column('id',
                              existing_type=sa.INTEGER(),
                              type_=sa.String(length=32),
                              existing_nullable=False)
        batch_op.alter_column('user_id',
                              existing_type=sa.INTEGER(),
                              type_=sa.String(length=32),
                              existing_nullable=False)
        batch_op.alter_column('target_image_id',
                              existing_type=sa.INTEGER(),
                              type_=sa.String(length=32),
                              existing_nullable=False)

    with op.batch_alter_table('gameplays', schema=None) as batch_op:
        batch_op.alter_column('id',
                              existing_type=sa.INTEGER(),
                              type_=sa.String(length=32),
                              existing_nullable=False)
        batch_op.alter_column('user_id',
                              existing_type=sa.INTEGER(),
                              type_=sa.String(length=32),
                              existing_nullable=True)

    with op.batch_alter_table('target_images', schema=None) as batch_op:
        batch_op.alter_column('id',
                              existing_type=sa.INTEGER(),
                              type_=sa.String(length=32),
                              existing_nullable=False)
        batch_op.alter_column('user_id',
                              existing_type=sa.INTEGER(),
                              type_=sa.String(length=32),
                              existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
                              existing_type=sa.INTEGER(),
                              type_=sa.String(length=32),
                              existing_nullable=False)

    # Update existing keys
    connection = op.get_bind()

    # Update gameplay_images foreign key references
    connection.execute('UPDATE gameplay_images '
                       'SET user_id = (SELECT id FROM users WHERE id = gameplay_images.user_id)')
    connection.execute('UPDATE gameplay_images '
                       'SET target_image_id = (SELECT id FROM target_images WHERE id = gameplay_images.target_image_id)')

    # Update gameplays foreign key references
    connection.execute('UPDATE gameplays '
                       'SET user_id = (SELECT id FROM users WHERE id = gameplays.user_id)')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
                              existing_type=sa.String(length=32),
                              type_=sa.INTEGER(),
                              existing_nullable=False)

    with op.batch_alter_table('target_images', schema=None) as batch_op:
        batch_op.alter_column('user_id',
                              existing_type=sa.String(length=32),
                              type_=sa.INTEGER(),
                              existing_nullable=False)
        batch_op.alter_column('id',
                              existing_type=sa.String(length=32),
                              type_=sa.INTEGER(),
                              existing_nullable=False)

    with op.batch_alter_table('gameplays', schema=None) as batch_op:
        batch_op.alter_column('user_id',
                              existing_type=sa.String(length=32),
                              type_=sa.INTEGER(),
                              existing_nullable=True)
        batch_op.alter_column('id',
                              existing_type=sa.String(length=32),
                              type_=sa.INTEGER(),
                              existing_nullable=False)

    with op.batch_alter_table('gameplay_images', schema=None) as batch_op:
        batch_op.alter_column('target_image_id',
                              existing_type=sa.String(length=32),
                              type_=sa.INTEGER(),
                              existing_nullable=False)
        batch_op.alter_column('user_id',
                              existing_type=sa.String(length=32),
                              type_=sa.INTEGER(),
                              existing_nullable=False)
        batch_op.alter_column('id',
                              existing_type=sa.String(length=32),
                              type_=sa.INTEGER(),
                              existing_nullable=False)

    # ### end Alembic commands ###
